### ISSUE TITLE
Linux/Raspberry/OpenWRT Version

### ISSUE THREAD

**Issue by EpicLPer** [kotylo/b315s-change-network#2]
Is there any chance you could make a similar thing for Linux/Raspberry and maybe OpenWRT (since it's also based on Linux)?

OpenWRT would be awesome since those routers run 24/7 in my network and could monitor it all the time, my Pi Zero too but I might disconnect it sometimes.

**Comment by kotylo** [comment]
Sorry, saw it too late. Good idea, but I've sold mine and thus no more interest in older modem. I hope you've found a solution to yours.
